# Generated by Django 3.2.6 on 2023-07-20 10:15

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
